name: Build OpenMPI and GROMACS

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  GROMACS_VERSION: "2023.1"
  MPI_VERSION: "4.1.5"

jobs:
  build_linux:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - run: mkdir artifacts
    - run: ls -la

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build
      uses: docker/build-push-action@v4
      with:
        push: false
        file: ${{github.workspace}}/manylinux.dockerfile

    - uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: artifacts
