name: Build GROMACS

on:
  workflow_dispatch:
  pull_request:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  GROMACS_VERSION: "2023.1"

jobs:
  build_linux:
    name: Build gromacs
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install git+https://github.com/nlesc-nano/nano-qmflows-manylinux@main

    - name: Python info
      run: |
        which python
        python --version

    - name: Installed packages
      run: pip list

    - name: build GROMACS
      run: python scripts/build_gromacs.py ${{ env.GROMACS_VERSION }}

    - uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: ubuntu-22.04_${{ env.GROMACS_VERSION }}.tar.gz
